//User login
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SERVER_RESPONSE_ERROR =
  "LOGIN_USER_SERVER_RESPONSE_ERROR";
export const LOGIN_USER_SERVER_RESPONSE_SUCCESS =
  "LOGIN_USER_SERVER_RESPONSE_SUCCESS";

//Register user
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

// Create new post
export const CREATE_COURSE = "CREATE_COURSE";
export const CREATE_COURSE_SERVER_RESPONSE_ERROR =
  "CREATE_COURSE_SERVER_RESPONSE_ERROR";
export const CREATE_COURSE_SERVER_RESPONSE_SUCCESS =
  "CREATE_COURSE_SERVER_RESPONSE_SUCCESS";

